### ISSUE TITLE
Request: Send prompts to text2img/img2img and generate negative prompts

### ISSUE THREAD

**Issue by gsgoldma** [imrayya/stable-diffusion-webui-Prompt_Generator#1]
can we have a way to automatically send a prompt to to text2img/img2img etc without copying and pasting?
and can it  also generate negative prompts?

**Comment by imrayya** [comment]
I'll write something to add a button to send the first generate prompt to text2img/img2img, should be done around tomorrow when I have time

Not sure about the negative prompts, because I'm just basing this off [FredZhang7's model](https://huggingface.co/FredZhang7/distilgpt2-stable-diffusion-v2) which isn't train to create negative prompts.

**Comment by imrayya** [comment]
The send to text2img/img2img buttons should be there now

The negative prompt seems to be outside the scope of the model so that will be closed until there's a new model that can handle that
