### ISSUE TITLE
Artist names

### ISSUE THREAD

**Issue by vis223** [imrayya/stable-diffusion-webui-Prompt_Generator#2]
Is there a way to limit the artist names being generated?
This is such a helpful extension as I'm a big fan of anything introducing randomness and saving on typing but I see the same artists all over the internet and don't want to join in with this trend. 
I know it's not your model but is there a way to opt in or out of using artists in the prompts?

**Comment by imrayya** [comment]
It really goes against the scope of the project because that would mess the underlining model which I didn't develop.

Do you think a possible solution is to have a _.txt_ file of a blacklist and you can artist names to that file. The extension will just delete the offending part of the prompt. I mean, then when you set the length, it won't be exactly right, but I think this a possible solution. I won't prepopulate the _blacklist.txt_ so it will be an opt in thing to remove artists (otherwise I would need a massive list of all possible artist and that's a bit much)

**Comment by floorcat** [comment]
I think user-configured blacklist.txt would be sufficient.

**Comment by vis223** [comment]
Thank you, that may be it

**Comment by vis223** [comment]
How would I go about setting up a blacklist? It's primarily the ones quickly becoming cliché I want to avoid. If I have to see the name Greg Rutkowski in a prompt one more time I think I may just lose it lol.

I would not ask you to spend any time filling out a DB of artists' names but a blacklist I can make myself would be a great compromise.

**Comment by imrayya** [comment]
If you update the extension, a new checkbox will should be there. 

Simply toggle the checkbox on and it should delete any offending part of the generated prompt. Again, there is the caveat of it won't replace any of the missing part with new words. It simply just deletes it

The blacklist is a text file in the extension folder called `blacklist.txt` (`.\extensions\stable-diffusion-webui-Prompt_Generator\blacklist.txt`)

**Comment by vis223** [comment]
Brilliant, thank you so much
